site_name: p2-concurrency

theme:
  name: material
  #name: mkdocs
  # custom_dir: material

  # 404 page
  static_templates:
  - 404.html
    
  navigation_depth: 3
  
  # Don't include MkDocs' JavaScript
  include_search_page: true
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - navigation.instant
    # - navigation.sections
    - navigation.tabs
  palette:
    scheme: default
    primary: teal
    accent: teal
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

plugins:
  - search
#  - git-revision-date-localized

nav:
  - exp1: exp1.md
  - exp2: exp2.md
#  - assign1: exp1-assignment.md
#  - assign2: exp2-assignment.md
  - /vtune: vtune.md
  - /cmake: cmake.md
  - /tracing: measurement.md
